### ISSUE TITLE
Error loading model

### ISSUE THREAD

**Issue by yu1chaofan** [intel-analytics/text-generation-webui#39]
### Describe the bug

![image](https://github.com/user-attachments/assets/faac9628-ee15-4878-9d2a-1fecfacdf680)
Error loading model

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Tested model: qwen1.5-0.5B phi-1_5 MiniCPM-2B-sft-bf16

### Logs

```shell
https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/webui_quickstart.md
```

### System Info

```shell
Windows 11 23H2
Intel(R) Arc(T M) A770 Graphics
```

**Comment by jason-dai** [comment]
I wonder if you can submit the issue to https://github.com/intel-analytics/ipex-llm/issues

**Comment by yu1chaofan** [comment]
OK, but I have successfully run MiniCPM-2B-sft-bf16 according to the following steps
https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/HuggingFace/LLM/minicpm
